# Generated by Django 4.2b1 on 2023-03-31 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Business",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("google_id", models.CharField(max_length=50, unique=True)),
                ("formatted_address", models.CharField(max_length=255)),
                ("formatted_address_last_verified_at", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "businesses",
            },
        ),
        migrations.CreateModel(
            name="Locality",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "localities",
            },
        ),
        migrations.CreateModel(
            name="Neighborhood",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=50, unique=True)),
            ],
            options={
                "verbose_name_plural": "neighborhoods",
            },
        ),
        migrations.CreateModel(
            name="PostalCode",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=5, unique=True)),
            ],
            options={
                "verbose_name_plural": "postal codes",
            },
        ),
        migrations.CreateModel(
            name="State",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(blank=True, max_length=2, unique=True)),
            ],
            options={
                "verbose_name_plural": "states",
            },
        ),
        migrations.CreateModel(
            name="BusinessAmenity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("serves_coffee", "Serves Coffee"),
                            ("serves_food", "Serves Food"),
                            ("serves_beer", "Serves Beer"),
                            ("serves_wine", "Serves Wine"),
                            ("serves_liquor", "Serves Liquor"),
                            ("is_takeout_only", "Is Takeout Only"),
                            ("allows_laptops", "Allows Laptops"),
                            ("has_wifi", "Has Wifi"),
                            ("has_tv", "Has Tv"),
                            ("can_play_sound", "Can Play Sound"),
                        ],
                        max_length=50,
                    ),
                ),
                ("is_supported", models.BooleanField(null=True)),
                ("last_verified_at", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "business",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="amenities",
                        to="businesses.business",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "business amenities",
            },
        ),
        migrations.AddField(
            model_name="business",
            name="locality",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="businesses.locality",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="neighborhood",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="businesses.neighborhood",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="postal_code",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="businesses.postalcode",
            ),
        ),
        migrations.AddField(
            model_name="business",
            name="state",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="businesses",
                to="businesses.state",
            ),
        ),
    ]
