# Generated by Django 4.2b1 on 2023-03-31 23:37

from django.db import migrations


def create_nyc_localities(apps, schema_editor):
    Locality = apps.get_model("businesses", "Locality")
    Locality.objects.create(value="New York")
    Locality.objects.create(value="Queens")
    Locality.objects.create(value="Brooklyn")


class Migration(migrations.Migration):
    dependencies = [
        ("businesses", "0003_auto_20230331_2336"),
    ]

    operations = [migrations.RunPython(create_nyc_localities)]
