---
steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - "--no-cache"
      - "-t"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - .
      - "-f"
      - "./Dockerfile"
    id: Build
  - name: gcr.io/cloud-builders/docker
    args:
      - push
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
    id: Push
  - name: gcr.io/google-appengine/exec-wrapper
    args:
      - "-i"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "-s"
      - "${PROJECT_ID}:${_DEPLOY_REGION}:${_INSTANCE_NAME}"
      - "-e"
      - "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}"
      - "--"
      - "python"
      - "manage.py"
      - "migrate"
    id: Migrate
  - name: gcr.io/google-appengine/exec-wrapper
    args:
      - "-i"
      - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - "-s"
      - "${PROJECT_ID}:${_DEPLOY_REGION}:${_INSTANCE_NAME}"
      - "-e"
      - "SETTINGS_NAME=${_SECRET_SETTINGS_NAME}"
      - "--"
      - "python"
      - "manage.py"
      - "collectstatic"
      - "--no-input"
    id: Collect static
  - name: gcr.io/google.com/cloudsdktool/cloud-sdk:slim
    args:
      - run
      - services
      - update
      - $_SERVICE_NAME
      - "--platform=managed"
      - "--image=$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
      - >-
        --labels=managed-by=gcp-cloud-build-deploy-cloud-run,commit-sha=$COMMIT_SHA,gcb-build-id=$BUILD_ID,gcb-trigger-id=$_TRIGGER_ID
      - "--region=$_DEPLOY_REGION"
      - "--quiet"
    id: Deploy
    entrypoint: gcloud

images:
  - "$_GCR_HOSTNAME/$PROJECT_ID/$REPO_NAME/$_SERVICE_NAME:$COMMIT_SHA"
