---
version: 2.1

jobs:
  test:
    docker:
      - image: cimg/python:3.10.6
        environment:
          DATABASE_URL: postgresql://postgres@localhost/circle_test
      - image: cimg/postgres:14.0
        environment:
          POSTGRES_USER: postgres
          POSTGRES_DB: circle_test
    steps:
      - checkout
      - run:
          name: install dependencies
          command: pip install -r requirements.txt
      - run:
          name: run tests
          command: pytest

workflows:
  build-and-test-workflow:
    jobs:
      - test
